pipeline:

  build-project:
    image: quay.io/ukhomeofficedigital/java8-mvn
    commands:
      - mvn -B -q clean package -DskipTests=true -DPROJECT_VERSION=1 -DBUILD_NUMBER=${DRONE_BUILD_NUMBER}
    when:
      event: [push, pull_request, tag]
    secrets:
      - artifactory_username
      - artifactory_password


  docker-build:
    image: docker:17.09.1
    environment:
    - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
    - docker build -t hocs-alfresco .
    when:
      branch: [master, refs/tags/*]
      event: [push, tag]

  install-docker-image:
    image: docker:17.09.1
    environment:
    - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets:
    - docker_password
    commands:
    - docker login -u="ukhomeofficedigital+hocs" -p=$${DOCKER_PASSWORD} quay.io
    - docker tag hocs-alfresco quay.io/ukhomeofficedigital/hocs-alfresco:build-$${DRONE_BUILD_NUMBER}
    - docker tag hocs-alfresco quay.io/ukhomeofficedigital/hocs-alfresco:latest
    - docker push quay.io/ukhomeofficedigital/hocs-alfresco:build-$${DRONE_BUILD_NUMBER}
    - docker push quay.io/ukhomeofficedigital/hocs-alfresco:latest
    when:
      branch: master
      event: push

  tag-docker-image-with-git-tag:
    image: docker:17.09.1
    environment:
    - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets:
    - docker_password
    commands:
    - docker login -u="ukhomeofficedigital+hocs" -p=$${DOCKER_PASSWORD} quay.io
    - docker tag hocs-alfresco quay.io/ukhomeofficedigital/hocs-alfresco:$${DRONE_TAG}
    - docker push quay.io/ukhomeofficedigital/hocs-alfresco:$${DRONE_TAG}
    when:
      event: tag

  clone-kube-project:
    image: plugins/git
    commands:
    - git clone https://github.com/UKHomeOffice/kube-hocs-alfresco.git
    when:
      event: [push, tag, deployment]

  deploy-to-dev-from-build-number:
    image: quay.io/ukhomeofficedigital/kd:v0.8.0
    environment:
    - KUBE_NAMESPACE=alf-dev
    - ENVIRONMENT=dev
    - VERSION=build-${DRONE_BUILD_NUMBER}
    - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
    secrets:
    - hocs_alfresco_dev
    commands:
    - cd kube-hocs-alfresco
    - ./deploy.sh
    when:
      branch: master
      event: [push, tag]

  deployment:
    image: quay.io/ukhomeofficedigital/kd:v0.8.0
    environment:
    - KUBE_NAMESPACE=alf-${DRONE_DEPLOY_TO}
    - ENVIRONMENT=${DRONE_DEPLOY_TO}
    - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
    secrets:
    - hocs_alfresco_dev
    - hocs_alfresco_qa
    commands:
    - cd kube-hocs-casework
    - ./deploy.sh
    when:
      event: deployment
      environment: [dev, qa]

  deploy-to-prod:
    image: quay.io/ukhomeofficedigital/kd:v0.8.0
    environment:
    - KUBE_NAMESPACE=alf-prod
    - ENVIRONMENT=prod
    - VERSION=${IMAGE_VERSION}
    - KUBE_SERVER=https://kube-api-prod.prod.acp.homeoffice.gov.uk
    secrets:
    - hocs_alfresco_prod
    commands:
    - cd kube-hocs-alfresco
    - ./deploy.sh
    when:
      event: deployment
      environment: prod
