version: '3.1'

services:

  mysql:
    image: mysql
    ports:
      - 3306:3306
    networks:
      - hocs-network
    environment:
      MYSQL_ROOT_PASSWORD: alfresco
      MYSQL_DATABASE: alfresco
      MYSQL_USER: alfresco
      MYSQL_PASSWORD: alfresco
    restart: always
    tmpfs:
      - /var/lib/mysql

  s3creator:
    image: garland/aws-cli-docker
    networks:
      - hocs-network
    entrypoint: "aws --endpoint-url http://localstack:80 s3 mb s3://UNSET"
    environment:
      AWS_ACCESS_KEY_ID: UNSET
      AWS_SECRET_ACCESS_KEY: UNSET
      AWS_DEFAULT_REGION: eu-west-1
    depends_on:
     - localstack

  localstack:
    image: localstack/localstack:latest
    ports:
      - 4572:80
      - 9080:8080
    networks:
      - hocs-network
    environment:
      HOSTNAME_EXTERNAL: localstack
      SERVICES: s3:80
      DEFAULT_REGION: eu-west-1

  alfresco:
    build:
      context: .
    environment:
      ALF_S3_ACCESSKEY: UNSET
      ALF_S3_SECRETKEY: UNSET
      ALF_S3_BUCKETNAME: UNSET
      ALF_S3_HOSTNAME: localstack
      ALF_DB_USERNAME: alfresco
      ALF_DB_PASSWORD: alfresco
      ALF_DB_NAME: alfresco
      ALF_DB_HOST: mysql
      ALF_DB_PORT: 3306
      ALF_ADMIN_INITIAL_PASSWORD: 209c6174da490caeb422f3fa5a7ae634
      ALF_REPORTING_ENDPOINT:
    depends_on:
      - s3creator
      - mysql
    ports:
      - 8083:8080
    networks:
      - hocs-network
    tmpfs:
      /usr/local/alfresco/alf_data

networks:
  hocs-network: