version: '3.1'

services:

  database:
    image: mysql

    ports:
      - 3306:3306

    networks:
      - alf-network

    environment:
      MYSQL_ROOT_PASSWORD: alfresco
      MYSQL_DATABASE: alfresco
      MYSQL_USER: alfresco
      MYSQL_PASSWORD: alfresco

    restart: always

    volumes:
      - dbdata:/var/lib/mysql

  alfresco:
    build:
      context: .

    depends_on:
      - database

    ports:
      - 9001:8080

    networks:
      - alf-network

networks:
  alf-network:

volumes:
  dbdata: {}